vscode_version = "1.98.2"

[[extensions]]
publisher_name = "bbenoist"
extension_name = "nix"

[[extensions]]
publisher_name = "catppuccin"
extension_name = "catppuccin-vsc"

[[extensions]]
publisher_name = "catppuccin"
extension_name = "catppuccin-vsc-icons"

[[extensions]]
publisher_name = "charliermarsh"
extension_name = "ruff"

[[extensions]]
publisher_name = "eamodio"
extension_name = "gitlens"

[[extensions]]
publisher_name = "editorconfig"
extension_name = "editorconfig"

[[extensions]]
publisher_name = "equinusocio"
extension_name = "vsc-material-theme"

[[extensions]]
publisher_name = "equinusocio"
extension_name = "vsc-material-theme-icons"

[[extensions]]
publisher_name = "github"
extension_name = "codespaces"

[[extensions]]
publisher_name = "github"
extension_name = "copilot"

[[extensions]]
publisher_name = "github"
extension_name = "copilot-chat"

[[extensions]]
publisher_name = "github"
extension_name = "copilot-workspace"

[[extensions]]
publisher_name = "github"
extension_name = "vscode-github-actions"

[[extensions]]
publisher_name = "github"
extension_name = "vscode-pull-request-github"

[[extensions]]
publisher_name = "golang"
extension_name = "go"

[[extensions]]
publisher_name = "hybridtalentcomputing"
extension_name = "cline-chinese"

[[extensions]]
publisher_name = "ms-azuretools"
extension_name = "vscode-docker"

[[extensions]]
publisher_name = "ms-ceintl"
extension_name = "vscode-language-pack-zh-hans"

[[extensions]]
publisher_name = "ms-python"
extension_name = "debugpy"

[[extensions]]
publisher_name = "ms-python"
extension_name = "python"

[[extensions]]
publisher_name = "ms-python"
extension_name = "vscode-pylance"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter-keymap"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter-renderers"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "vscode-jupyter-cell-tags"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "vscode-jupyter-slideshow"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-containers"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-ssh"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-ssh-edit"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-wsl"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "vscode-remote-extensionpack"

[[extensions]]
publisher_name = "ms-vscode"
extension_name = "powershell"

[[extensions]]
publisher_name = "ms-vscode"
extension_name = "remote-explorer"

[[extensions]]
publisher_name = "ms-vscode"
extension_name = "remote-server"

[[extensions]]
publisher_name = "redhat"
extension_name = "vscode-yaml"

[[extensions]]
publisher_name = "rust-lang"
extension_name = "rust-analyzer"

[[extensions]]
publisher_name = "tamasfe"
extension_name = "even-better-toml"

[[extensions]]
publisher_name = "thinker"
extension_name = "sort-json"

[[extensions]]
publisher_name = "tomjs"
extension_name = "vscode-reload"

[[extensions]]
publisher_name = "usernamehw"
extension_name = "errorlens"

[[extensions]]
publisher_name = "ziglang"
extension_name = "vscode-zig"

[[extensions]]
publisher_name = "zxh404"
extension_name = "vscode-proto3"

