# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{
  pkgs,
  lib,
}: let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
  merge
  (merge
    (merge
      (merge
        {
          "bbenoist"."nix" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix";
            publisher = "bbenoist";
            version = "1.0.1";
            sha256 = "0zd0n9f5z1f0ckzfjr38xw2zzmcxg1gjrava7yahg5cvdcw6l35b";
          };
          "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
            name = "catppuccin-vsc";
            publisher = "catppuccin";
            version = "3.16.1";
            sha256 = "14pb2d21c6hiw43hbmliq061nhrm2bghrklnjkfmwny3rpki0k58";
          };
          "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
            name = "catppuccin-vsc-icons";
            publisher = "catppuccin";
            version = "1.20.0";
            sha256 = "0v69n8nhn9ay96aq9xz41cf06rgwcp5q5g8fpi0h5cvggvjiljlf";
          };
          "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
            name = "gitlens";
            publisher = "eamodio";
            version = "16.3.3";
            sha256 = "14pr7zmdpj7939w5625p13h6j7aacjv414cnvmfxljarr1lc9kwx";
          };
          "editorconfig"."editorconfig" = vscode-utils.extensionFromVscodeMarketplace {
            name = "editorconfig";
            publisher = "editorconfig";
            version = "0.17.2";
            sha256 = "1s0a2zgxk6qxl6lzw6klkn8xhsxk0l87vcbms2k8535kvscbwbay";
          };
          "equinusocio"."vsc-material-theme" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vsc-material-theme";
            publisher = "equinusocio";
            version = "34.7.9";
            sha256 = "0a2hjd552b2fbfkm3wcvf5rh6dl4wb9kdrmdji4yx9jvqh2di60z";
          };
          "equinusocio"."vsc-material-theme-icons" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vsc-material-theme-icons";
            publisher = "equinusocio";
            version = "3.8.12";
            sha256 = "0srj5d5mkfpcz4sissk5gbs4ijjlr7hqfjwmqa6rxslrgjihdb5g";
          };
          "github"."codespaces" = vscode-utils.extensionFromVscodeMarketplace {
            name = "codespaces";
            publisher = "github";
            version = "1.17.3";
            sha256 = "1g4b7gd24cifmh62v1dj1b79yp5z6jbffmwh2nlymjbqf9h4bll9";
          };
          "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
            name = "copilot";
            publisher = "github";
            version = "1.292.0";
            sha256 = "01acxvk6yc23x8dfic8fpw0cr4lhl53sk0lynp3f8wf88qq8633f";
          };
          "github"."copilot-chat" = vscode-utils.extensionFromVscodeMarketplace {
            name = "copilot-chat";
            publisher = "github";
            version = "0.25.1";
            sha256 = "0qq55khxbn0r778sifbnbd3g8bv06012dixhhybdh74851zfj7vp";
          };
          "github"."copilot-workspace" = vscode-utils.extensionFromVscodeMarketplace {
            name = "copilot-workspace";
            publisher = "github";
            version = "0.5.4";
            sha256 = "0r9v4wbd0kz8bl1xwb5mva5swvzyxf8vsnvdppvw78v1ipcd6993";
          };
          "github"."vscode-pull-request-github" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-pull-request-github";
            publisher = "github";
            version = "0.106.0";
            sha256 = "07xlq6y3czj871sxlahzkyw9ajjl9fmflhpqvv2qlixlzs3rqvaf";
          };
          "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
            name = "go";
            publisher = "golang";
            version = "0.46.1";
            sha256 = "1fx6il5mpl6z2y68s63ssy28k8hhkj998r3rpajpckqnygm85527";
          };
          "hybridtalentcomputing"."cline-chinese" = vscode-utils.extensionFromVscodeMarketplace {
            name = "cline-chinese";
            publisher = "hybridtalentcomputing";
            version = "3.4.14";
            sha256 = "021y6klhacyvjjwifjrqgin0rw8kd1p2iypzmm7v49s0ffnpli2b";
          };
          "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-docker";
            publisher = "ms-azuretools";
            version = "1.29.4";
            sha256 = "1nhrp43gh4pwsdy0d8prndx2l0mrczf1kirjl1figrmhcp7h4q4g";
          };
          "ms-ceintl"."vscode-language-pack-zh-hans" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-language-pack-zh-hans";
            publisher = "ms-ceintl";
            version = "1.98.2025031209";
            sha256 = "0qar7fmxai1wbbrs8rvhi91b1378gd9n3i3nrran4is6abn5n2q9";
          };
          "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-pylance";
            publisher = "ms-python";
            version = "2025.3.2";
            sha256 = "0sa1xznwd0f8kq326siyipd25a2jsqj66ykap3hk9cqqbf40gzif";
          };
          "ms-toolsai"."jupyter-keymap" = vscode-utils.extensionFromVscodeMarketplace {
            name = "jupyter-keymap";
            publisher = "ms-toolsai";
            version = "1.1.2";
            sha256 = "02rb4r5zspicj2c7ffrr6xj6dmk0948lnl2f8f89xlfrkh2z44pl";
          };
          "ms-toolsai"."jupyter-renderers" = vscode-utils.extensionFromVscodeMarketplace {
            name = "jupyter-renderers";
            publisher = "ms-toolsai";
            version = "1.1.0";
            sha256 = "0i44ks8bd67ywbx300jcd74680fr2ccvmkbhqzisar6m78kk24g0";
          };
          "ms-toolsai"."vscode-jupyter-cell-tags" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-jupyter-cell-tags";
            publisher = "ms-toolsai";
            version = "0.1.9";
            sha256 = "1xm8l6wrfqird8pdw7gm2l604iqdwbc2cd2pri9l1nmbncaxpq2w";
          };
          "ms-toolsai"."vscode-jupyter-slideshow" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-jupyter-slideshow";
            publisher = "ms-toolsai";
            version = "0.1.6";
            sha256 = "1hqan5ax3dl1anl0fva4df79609r83d7g325rn0kwxqqnyp0qyvy";
          };
          "ms-vscode"."powershell" = vscode-utils.extensionFromVscodeMarketplace {
            name = "powershell";
            publisher = "ms-vscode";
            version = "2025.0.0";
            sha256 = "141n9zpabm76l940ap5x9wf5906bx6548slb6jncyf5d4ismybd8";
          };
          "ms-vscode"."remote-explorer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-explorer";
            publisher = "ms-vscode";
            version = "0.4.3";
            sha256 = "12dwyl03gcsrn8fkr8vfixdkyfyyznbkvwblwzh74nf0978abggg";
          };
          "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-containers";
            publisher = "ms-vscode-remote";
            version = "0.401.0";
            sha256 = "0b2f95swfy01ycqr7jd4yc4x5r6ac0m9p8k1acqp13zvwjn69sck";
          };
          "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-ssh";
            publisher = "ms-vscode-remote";
            version = "0.118.0";
            sha256 = "0lfdfbbv9k0ds5j092jc0i3rakgxigyb6i8ricznw8jzbs70wyrc";
          };
          "ms-vscode-remote"."remote-ssh-edit" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-ssh-edit";
            publisher = "ms-vscode-remote";
            version = "0.87.0";
            sha256 = "1qqsnzn9z11jr72n7cl0ab6i9mv49c0ijcp699zbglv5092gmrf9";
          };
          "ms-vscode-remote"."remote-wsl" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-wsl";
            publisher = "ms-vscode-remote";
            version = "0.88.5";
            sha256 = "01ajd3pg0a2nfdbfqfbzcix3alr8wpzymqgqlmqyv34fhr2hcc6d";
          };
          "ms-vscode"."remote-server" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-server";
            publisher = "ms-vscode";
            version = "1.5.2";
            sha256 = "0llrl0s9fll17sc1fxx5ndk5l9x25k4ln1gahpc7ljwhykyzg9hs";
          };
          "ms-vscode-remote"."vscode-remote-extensionpack" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-remote-extensionpack";
            publisher = "ms-vscode-remote";
            version = "0.26.0";
            sha256 = "0xjld7p1zg9zybcw47xzrikgyc3hp9lfk6vbrm0syba8n90k8jk1";
          };
          "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "even-better-toml";
            publisher = "tamasfe";
            version = "0.21.2";
            sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";
          };
          "thinker"."sort-json" = vscode-utils.extensionFromVscodeMarketplace {
            name = "sort-json";
            publisher = "thinker";
            version = "20.1.0";
            sha256 = "11gzsrm38yicqdg1kld5lgyjx3zqcw9v1xca5lma4wn1d4jx8a2h";
          };
          "tomjs"."vscode-reload" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-reload";
            publisher = "tomjs";
            version = "0.2.0";
            sha256 = "0fs7lmxwldq5p42kjf2sih5wlxj7h43bwkkndm92jhbs5zwwy4sj";
          };
          "usernamehw"."errorlens" = vscode-utils.extensionFromVscodeMarketplace {
            name = "errorlens";
            publisher = "usernamehw";
            version = "3.24.0";
            sha256 = "00avhl46r5kv51f7pbn5jlhpr1rfx2iwmfjfdsvgyv63i93mg75g";
          };
          "ziglang"."vscode-zig" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-zig";
            publisher = "ziglang";
            version = "0.6.6";
            sha256 = "16fjwj71akkw6pfbxrbiq8ycnsld51fdx0h7i3x5rv79qi3c45jk";
          };
          "zxh404"."vscode-proto3" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-proto3";
            publisher = "zxh404";
            version = "0.5.5";
            sha256 = "08gjq2ww7pjr3ck9pyp5kdr0q6hxxjy3gg87aklplbc9bkfb0vqj";
          };
        }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "charliermarsh"."ruff" = vscode-utils.extensionFromVscodeMarketplace {
            name = "ruff";
            publisher = "charliermarsh";
            version = "2025.22.0";
            sha256 = "1i2bp6k3s2fs9yadd5hlv32fisnf322kfv9mn6xvk299rrjpyrcl";
            arch = "linux-x64";
          };
          "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
            name = "debugpy";
            publisher = "ms-python";
            version = "2025.4.1";
            sha256 = "0xwp2f18nsbj4bla0vnzhmim2w4lfbnf930cw8cbbsgh8gsmvsdx";
            arch = "linux-x64";
          };
          "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
            name = "python";
            publisher = "ms-python";
            version = "2025.2.0";
            sha256 = "0bvsf99syy800zzrgkbqlsziz7ndy3z5h2zbdaqvq2wzpncwx4l0";
            arch = "linux-x64";
          };
          "ms-toolsai"."jupyter" = vscode-utils.extensionFromVscodeMarketplace {
            name = "jupyter";
            publisher = "ms-toolsai";
            version = "2025.2.0";
            sha256 = "0qyz3c1r5xylsixgs9l67v90jv59ywifqj107h9nppgl9wag5z62";
            arch = "linux-x64";
          };
          "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rust-analyzer";
            publisher = "rust-lang";
            version = "0.3.2353";
            sha256 = "17v14ndf3hagnq9ry5c410clsh4cl8kxbhm5ybf50j6dz4yw6vv2";
            arch = "linux-x64";
          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "charliermarsh"."ruff" = vscode-utils.extensionFromVscodeMarketplace {
          name = "ruff";
          publisher = "charliermarsh";
          version = "2025.22.0";
          sha256 = "1571a6b1wyfrxdmmq1mnn1prjbkm6zaidys24mdr0kq36hd47bq9";
          arch = "linux-arm64";
        };
        "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
          name = "debugpy";
          publisher = "ms-python";
          version = "2025.4.1";
          sha256 = "1637vxsb8rd567jp6af9gfpaj4iam8al79r52v137xyakijxy1ws";
          arch = "linux-arm64";
        };
        "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
          name = "python";
          publisher = "ms-python";
          version = "2025.2.0";
          sha256 = "0chchcrzi4sgvz5n8v38gkg661z3wvjhc02pq82ydvwgvdp1ymw8";
          arch = "linux-arm64";
        };
        "ms-toolsai"."jupyter" = vscode-utils.extensionFromVscodeMarketplace {
          name = "jupyter";
          publisher = "ms-toolsai";
          version = "2025.2.0";
          sha256 = "1pqn6xs3z04ijpph9n5acbs2hwijbgk644wqka68dmnsb2rp65vn";
          arch = "linux-arm64";
        };
        "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-analyzer";
          publisher = "rust-lang";
          version = "0.3.2353";
          sha256 = "1hh2cd7vkhj4dmfjdbp5jric9c7wscw4qn3x0mkqybwbdw1z07n2";
          arch = "linux-arm64";
        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "charliermarsh"."ruff" = vscode-utils.extensionFromVscodeMarketplace {
        name = "ruff";
        publisher = "charliermarsh";
        version = "2025.22.0";
        sha256 = "17ldg6hs1754dnmillldpwnv6d1dbc3vfzdivf5p6l2mkx62ymw7";
        arch = "darwin-x64";
      };
      "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
        name = "debugpy";
        publisher = "ms-python";
        version = "2025.4.1";
        sha256 = "15kbwigy6kf2g9pgaszrx9hnjli9bk10x8fhx9c7f6y09rvw76d1";
        arch = "darwin-x64";
      };
      "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
        name = "python";
        publisher = "ms-python";
        version = "2025.2.0";
        sha256 = "1r31r72s92a7hp39lb4rqh2h2ly5b7qirsc8vd4a41jzx9sxdwxc";
        arch = "darwin-x64";
      };
      "ms-toolsai"."jupyter" = vscode-utils.extensionFromVscodeMarketplace {
        name = "jupyter";
        publisher = "ms-toolsai";
        version = "2025.2.0";
        sha256 = "06rz83mvs5pnyxzaadrbrgg92jszz96vx7z373mpmm4zgm670ipv";
        arch = "darwin-x64";
      };
      "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
        name = "rust-analyzer";
        publisher = "rust-lang";
        version = "0.3.2353";
        sha256 = "036xsdmb0a4hjhnsjacayin837pvaik915zq9m9g0ga48c5jcaj2";
        arch = "darwin-x64";
      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "charliermarsh"."ruff" = vscode-utils.extensionFromVscodeMarketplace {
      name = "ruff";
      publisher = "charliermarsh";
      version = "2025.22.0";
      sha256 = "0zqnnn33kpg9jh3ffph6lh226rvqq6402wjiy2809i7257zv41pi";
      arch = "darwin-arm64";
    };
    "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
      name = "debugpy";
      publisher = "ms-python";
      version = "2025.4.1";
      sha256 = "06wsz5xclzsn2c1dvgfq4jv1wxp61p8x4p4agqpcnsqqx4sica00";
      arch = "darwin-arm64";
    };
    "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
      name = "python";
      publisher = "ms-python";
      version = "2025.2.0";
      sha256 = "1jj7ak88g4c36czxq0wxqlva5maks8qh7nsi4ssbav7l5ydm4g8d";
      arch = "darwin-arm64";
    };
    "ms-toolsai"."jupyter" = vscode-utils.extensionFromVscodeMarketplace {
      name = "jupyter";
      publisher = "ms-toolsai";
      version = "2025.2.0";
      sha256 = "1ljfp0y068ww3pjbjyrz877ls2da9spn2cj5di6nsqjkcklzsh59";
      arch = "darwin-arm64";
    };
    "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
      name = "rust-analyzer";
      publisher = "rust-lang";
      version = "0.3.2353";
      sha256 = "0clh93mb205nmgvmrl51qxx1vxb9yjfz54pzxip7mvvmp21zjsxz";
      arch = "darwin-arm64";
    };
  })
