# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{
  pkgs,
  lib,
}: let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
  merge
  (merge
    (merge
      (merge
        {
          "bbenoist"."nix" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix";
            publisher = "bbenoist";
            version = "1.0.1";
            sha256 = "0zd0n9f5z1f0ckzfjr38xw2zzmcxg1gjrava7yahg5cvdcw6l35b";
          };
          "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
            name = "catppuccin-vsc";
            publisher = "catppuccin";
            version = "3.16.1";
            sha256 = "14pb2d21c6hiw43hbmliq061nhrm2bghrklnjkfmwny3rpki0k58";
          };
          "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
            name = "catppuccin-vsc-icons";
            publisher = "catppuccin";
            version = "1.20.0";
            sha256 = "0v69n8nhn9ay96aq9xz41cf06rgwcp5q5g8fpi0h5cvggvjiljlf";
          };
          "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
            name = "go";
            publisher = "golang";
            version = "0.46.1";
            sha256 = "1fx6il5mpl6z2y68s63ssy28k8hhkj998r3rpajpckqnygm85527";
          };
          "ms-ceintl"."vscode-language-pack-zh-hans" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-language-pack-zh-hans";
            publisher = "ms-ceintl";
            version = "1.98.2025031209";
            sha256 = "0qar7fmxai1wbbrs8rvhi91b1378gd9n3i3nrran4is6abn5n2q9";
          };
        }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {}))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {}))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {}))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {})
